# Menus
menu:
  Homepage: https://www.holten.site
  Blog: https://blog.holten.site
  Github: https://github.com/holtenko/
  Wiki: https://wiki.holten.site

# Customize
customize:
    logo:
        enabled: true
        width: 35
        height: 35
        url: /img/logo.png
    profile:
        enabled: true # Whether to show profile bar
        avatar: /img/logo.png # css/images/avatar.png
        gravatar: # Gravatar email address, if you enable Gravatar, your avatar config will be overriden
        author: holten ko
        author_title: Software Engineer
        location: Shanghai, China
        follow: https://github.com/holtenko/
    highlight: monokai
    sidebar: left # sidebar position, options: left, right
    category_perExpand: false # enable article categories list per expanding
    thumbnail: false # enable posts thumbnail, options: true, false
    favicon: /favicon.ico # path to favicon
    default_index_file: index.md # if this, it will display at site index instead of default index page
    social_links:
        github: https://github.com/holtenko
        stack-overflow: https://stackoverflow.com/users/6351396/holten?tab=profile
        rss: /atom.xml
    social_link_tooltip: true # enable the social link tooltip, options: true, false

# Widgets
widgets: # default use category only
    - category
    # - recent_posts
    # - archive
    # - tag
    # - tagcloud
    # - links
    
# Excerpt 
## Auto creat excerpt with not <!--more-->
## Enable will truncate auto_excerpt.lines rows in post head to replace excerpt.
auto_excerpt:
    enable: true
    lines: 5

# Search
search:
    insight: true # you need to install `hexo-generator-json-content` before using Insight Search
    swiftype: # enter swiftype install key here
    baidu: false # you need to disable other search engines to use Baidu search, options: true, false

# History version 
history_control: # make you wiki has history version control in page
    enable: true
    server_link: https://github.com # recommend use GitHub https://github.com
    user: holtenko
    repertory: wiki
    branch: source

# Comment
comment:
    disqus: # enter disqus shortname here
    duoshuo: # enter duoshuo shortname here
    youyan: # enter youyan uid here

# Share
share: default # options: jiathis, bdshare, addtoany, default

#Count
busuanzi_count:
    enable: true

# Plugins
plugins:
    lightgallery: true # options: true, false
    justifiedgallery: true # options: true, false
    mathjax: true # options: true, false - to enable use Mathjax in your article
    google_analytics: # enter the tracking ID for your Google Analytics
    google_site_verification: # enter Google site verification code
    baidu_analytics: # enter Baidu Analytics hash key

# Miscellaneous
miscellaneous:
    open_graph: # see http://ogp.me
        fb_app_id:
        fb_admins:
        twitter_id:
        google_plus:
    links:
